apiVersion: v1
kind: Service
metadata:
  name: postgress-service
  labels:
    name: postgress-service
    app: voter-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgress-db-pod
    app: voter-app
