apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgress-db-pod
    app: voter-app
spec:
  containers:
    - name: postgress-db
      image: postgress:9.4
      ports:
        - containerPort: 5432