apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis-db-pod
    app: voter-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379