apiVersion: v1
kind: Pod
metadata:
  name: voter-app-pod
  labels:
    app: voter-app-demo
    name: voter-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80



