apiVersion: v1
kind: Pod
metadata:
  name: Worker-app-pod
  lables:
    app: voter-app
    name: Worker-app-pod

spec:
  containers:
    - name: Worker-app
      image: dockersamples/examplevotingapp_worker
